[project]
name = "jaxus"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.1.0",
    "imagelib",
    "jax[cuda12]>=0.5.1",
    "matplotlib>=3.5.0",
    "numpy>=1.8.0",
    "optax>=0.2.4",
    "rich>=13.9.4",
    "tcl>=0.2",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = ["black>=25.1.0", "isort>=6.0.1", "pytest>=8.3.4"]

[tool.uv.sources]
imagelib = { git = "https://github.com/vincentvdschaft/imagelib", rev = "main" }
