[project]
name = "jaxus"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py",
    "imagelib",
    "jax[cuda12]",
    "matplotlib",
    "numpy",
    "optax",
    "rich",
    "tqdm",
]

[dependency-groups]
dev = ["black>=25.1.0", "isort>=6.0.1", "pytest>=8.3.4"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
imagelib = { git = "https://github.com/vincentvdschaft/imagelib", rev = "main" }
